import { chromium } from "playwright-core";
const OUT = "/home/Allie/develop/daggler/docs/images";
const browser = await chromium.launch({ executablePath: process.env.CHROME, args:["--no-sandbox","--force-color-profile=srgb"] });
const ctx = await browser.newContext({ viewport:{width:1500,height:980}, deviceScaleFactor:2, colorScheme:"dark" });
const page = await ctx.newPage();
await page.goto("http://localhost:3737/map", { waitUntil:"networkidle" });
await page.getByText("Try the demo corpus").click();
await page.waitForSelector("text=demo corpus", { timeout: 15000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: OUT + "/automation-map.png" });
console.log("automation-map.png captured");
await browser.close();
